// flow-typed signature: 612f9cef099996ea4fb3af146e6af029
// flow-typed version: <<STUB>>/stylelint-custom-processor-loader_v^0.5.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-custom-processor-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-custom-processor-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-custom-processor-loader/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-custom-processor-loader/dist/index.js' {
  declare module.exports: $Exports<
    'stylelint-custom-processor-loader/dist/index'
  >;
}
